
stages:
  - mirror_push

variables:
  GITHUB_MIRROR_TOKEN:
    description: "GitHub token for mirroring"
  GITHUB_MIRROR_URL: 
    value: github.com/0xleft/genalphalang.git
    description: "GitHub URL for mirroring"

default:
  image: ubuntu:latest

mirror_push:
  stage: mirror_push
  tags:
    - docker-builder
  script:
    - apt-get update
    - apt-get install -y git
    - git checkout main
    - git pull http://bobik.squidwock.com/root/genalphalang.git
    - git push https://x-access-token:$GITHUB_MIRROR_TOKEN@$GITHUB_MIRROR_URL
  only:
    - main