
stages:
  - mirror_push

variables:
  GITHUB_MIRROR_TOKEN:
    description: "GitHub token for mirroring"
  GITHUB_MIRROR_URL: 
    value: https://github.com/0xleft/genalphalang.git
    description: "GitHub URL for mirroring"

default:
  image: ubuntu:latest

mirror_push:
  stage: mirror_push
  tags:
    - docker-builder
  script:
    - apt-get update -y
    - apt-get install -y gh
    - GH_TOKEN=$GITHUB_MIRROR_TOKEN gh auth login 
    - git remote add mirror $GITHUB_MIRROR_URL
    - git push --mirror mirror
  only:
    - main