
stages:
  - mirror_push

variables:
  GITHUB_MIRROR_TOKEN:
    description: "GitHub token for mirroring"
  GITHUB_MIRROR_URL: 
    value: https://x-access-token:$GITHUB_MIRROR_TOKEN@github.com/0xleft/genalphalang.git
    description: "GitHub URL for mirroring"

default:
  image: ubuntu:latest

mirror_push:
  stage: mirror_push
  tags:
    - docker-builder
  script:
    - git remote add mirror $GITHUB_MIRROR_URL
    - git push --mirror mirror
  only:
    - main