name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run go build
        run: go build -v -o gal
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: gal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}